lab4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myweb/', include('myweb.urls')),
    path('', include('myweb.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myweb/urls.py
from django.urls import path
from . import views

app_name = 'myweb'
urlpatterns = [
    path('', views.index, name='index'),
    path('portofolio', views.portofolio, name='portofolio'),
    path('about', views.about, name='about'),
    path('message', views.message, name='message'),
    path('login', views.login, name='login'),
    path('signup', views.signup, name='signup'),
    path('create_sched', views.create_sched, name = 'create_sched'),
    path('sched_post', views.sched_post, name = 'sched_post'),
    path('view_sched', views.view_sched, name = 'view_sched'),
    path('delete_all_sched_db', views.delete_all_sched_db, name = 'delete_all_sched_db'),
]

myweb/models.py
from django.db import models
from django.utils import timezone


class Schedule(models.Model):
    event_name = models.CharField(max_length = 30)
    event_date = models.DateField()
    event_time = models.TimeField()
    event_category = models.CharField(max_length = 30)
    event_place = models.CharField(max_length = 30)
    created_date = models.DateTimeField(default = timezone.now)

    def __str__(self):
        return 'Event Name : ' + self.event_name

myweb/forms.py
from django import forms

class Sched_form(forms.Form):
    error_msg = {
        'required' : 'Please fill the blank section',
        'invalid' : 'Please fill correctly'
    }

    attrs = {
        'class' : 'form-control'
    }

    event_name = forms.CharField(
        label = 'Event Name',
        max_length = 30,
        widget = forms.TextInput(attrs = attrs)
    )
    
    event_date = forms.DateField(
        label = 'Date',
        widget = forms.DateInput(attrs = {'type':'date'})
    )

    event_time = forms.TimeField(
        label = 'Time',
        widget = forms.TimeInput(attrs = {'type':'time'})
    )

    event_category = forms.CharField(
        label = 'category',
        max_length = 30,
        widget = forms.TextInput(attrs = attrs)
    )

    event_place = forms.CharField(
        label = 'Place',
        max_length = 30,
        widget = forms.TextInput(attrs = attrs)
    )

myweb/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Sched_form
from .models import Schedule

# Create your views here.
def default_response():
    response = {
        'title':'',
        'homstat':'',
        'porstat':'',
        'abtstat':'',
        'msgstat':'',
        'scdstat':'',
    }
    return response

def index(request):
    response = default_response()
    response['title'] = 'Home'
    response['homstat'] = 'active-self'
    return render(request, 'index.html', response)


def portofolio(request):
    response = default_response()
    response['title'] = 'Portofolio'
    response['porstat'] = 'active-self'
    return render(request, 'portofolio.html', response)


def about(request):
    response = default_response()
    response['title'] = 'About'
    response['abtstat'] = 'active-self'
    return render(request, 'about.html', response)


def message(request):
    response = default_response()
    response['title'] = 'Message'
    response['msgstat'] = 'active-self'
    return render(request, 'message.html', response)


def login(request):
    response = {}
    return render(request, 'login.html', response)


def signup(request):
    response = {}
    return render(request, 'register.html', response)

def create_sched(request):
    response = {}
    response['title'] = 'Create Schedule'
    response['schedule_form'] = Sched_form
    return render(request, 'create_sched.html', response)

def sched_post(request):
    response = {}
    form = Sched_form(request.POST or None)

    if (request.method == 'POST' and form.is_valid()):
        response['event_name'] = request.POST['event_name']
        response['event_date'] = request.POST['event_date']
        response['event_time'] = request.POST['event_time']
        response['event_category'] = request.POST['event_category']
        response['event_place'] = request.POST['event_place']
        
        schedule = Schedule(
            event_name = response['event_name'], 
            event_date = response['event_date'],
            event_time = response['event_time'],
            event_category = response['event_category'],
            event_place = response['event_place']
        )
        schedule.save()
        response1 = {}
        schedule = Schedule.objects.all()
        response1['schedule'] = schedule
        response1['showpopup'] = 'visibilty: block'
        response1['word'] = "Forms has been updated!"
        html = 'view_sched.html'
        return render(request, html, response1)
    
    else:
        return HttpResponseRedirect('/')

def view_sched(request):
    response = {}
    schedule = Schedule.objects.all()
    response['title'] = 'Schedule'
    response['schedule'] = schedule
    response['showpopup'] = 'visibility: hidden'
    html = 'view_sched.html'
    return render(request, html , response)


def delete_all_sched_db(request):
    Schedule.objects.all().delete()
    response = {}
    response['title'] = 'Schedule'
    response['showpopup'] = 'visibilty: block'
    response['word'] = "Forms has been deleted!"
    html = 'view_sched.html'
    return render(request, html, response)

myweb/templates/about.html
{% extends "base.html" %}

{% block main %}

<div class="content grid-x">
    <div class="cell medium-4" style="background-color: #ECF0F1">

    </div>
    <div class="cell medium-7 about-self grid-x text-center">
        <div class="cell medium-12 grid-x item-on-about">
            <div class="cell medium-12">
                <!-- <div class="line-about"></div> -->
                <div>
                    <svg style="margin: 10px;" xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 24 24"><path d="M12 2c2.757 0 5 2.243 5 5.001 0 2.756-2.243 5-5 5s-5-2.244-5-5c0-2.758 2.243-5.001 5-5.001zm0-2c-3.866 0-7 3.134-7 7.001 0 3.865 3.134 7 7 7s7-3.135 7-7c0-3.867-3.134-7.001-7-7.001zm6.369 13.353c-.497.498-1.057.931-1.658 1.302 2.872 1.874 4.378 5.083 4.972 7.346h-19.387c.572-2.29 2.058-5.503 4.973-7.358-.603-.374-1.162-.811-1.658-1.312-4.258 3.072-5.611 8.506-5.611 10.669h24c0-2.142-1.44-7.557-5.631-10.647z"/></svg>
                </div>
                <!-- <div class="line-about"></div> -->
            </div>
            <div class="cell medium -12">
                <p> Curios and organized person who has passion in technology, great listener, enjoy working with a lot of different people, and also a creative thinker. </p>
            </div>
        </div>
        
        <div class="cell medium-12 grid-x item-on-about">
            <div class="cell medium-12">
                <h1><svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 24 24"><path d="M20 12.875v5.068c0 2.754-5.789 4.057-9 4.057-3.052 0-9-1.392-9-4.057v-6.294l9 4.863 9-3.637zm-8.083-10.875l-12.917 5.75 12 6.5 11-4.417v7.167h2v-8.25l-12.083-6.75zm13.083 20h-4c.578-1 1-2.5 1-4h2c0 1.516.391 2.859 1 4z"/></svg></h1>
            </div>
            <div class="medium-12">
                <p>Faculty of Computer Science, University of Indonesia — Bachelor
                    <br> JULY 2017 - PRESENT</p>
            </div>
        </div>
                            
        <div class="cell medium-12 grid-x item-on-about">
            <div class="cell medium-12">
                <h1><svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 24 24"><path d="M4.104 0l-4.104 4.152 18.888 18.799 5.112 1.049-.961-5.203-18.935-18.797zm15.946 21.502c-.167.166-.436.166-.602 0l-17.262-17.124c-.167-.167-.167-.435-.001-.603.166-.166.437-.166.603 0l17.262 17.126c.167.165.166.435 0 .601zm1.544-2.132c.166.166.166.437 0 .603-.166.165-.436.166-.602 0l-17.263-17.126c-.165-.165-.165-.435 0-.601.167-.166.436-.166.601-.001l17.264 17.125zm-2.855-14.067c-.195-.195-.195-.512 0-.707s.512-.195.707 0 .195.512 0 .707-.511.196-.707 0zm-7.734 12.641l-6.055 6.056-4.95-4.908 6.059-6.059 1.419 1.41-.407.407.707.707-.707.707-.707-.707-.707.707.707.707-.707.707-.707-.707-.707.707.707.707-.707.707-.707-.707-.707.708 2.121 2.121 4.657-4.657 1.398 1.387zm2.035-11.892l6.052-6.052 4.908 4.95-6.013 6.014-1.398-1.388 4.625-4.625-2.121-2.121-2.121 2.12.707.707-.708.708-.707-.707-.707.707.707.707-.707.707-.707-.708-.39.39-1.42-1.409z"/></svg></h1>
            </div>
            <div class="cell medium-6">
                <p>
                    Python<br>
                    Java<br>
                    Pascal
                </p>
            </div>
            <div class="cell medium-6">
                <p>
                    HTML5
                    <br>
                    CSS3
                    <br>
                    JavaScript
                </p>
            </div>
        </div> 
        
    </div>
    
</div>

{% endblock %}

myweb/templates/base.html
{% load static %}
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" type="text/css" href="{%static "css/app.css" %}">
        <link rel="stylesheet" type="text/css" href="{%static "css/foundation.css" %}">
        <link rel="stylesheet" type="text/css" href="{%static "css/foundation.min.css" %}">
        <link rel="stylesheet" type="text/css" href="{%static "css/style.css" %}">
        <link rel="stylesheet" type="text/css" href="{%static "css/styleacc.css" %}">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" rel="stylesheet">
        <title>
            {{ title }}
        </title>
        <script src="{%static "js/app.js" %}"></script>
        <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    </head>

    <body>
        <div class="title-bar grid-x" data-responsive-toggle="example-menu" data-hide-for="medium">
            <div class="cell small-6">
                <h1>PROFILE</h1>
            </div>
            <div class="logo-self cell small-6">
                <button class="menu-icon" type="button" data-toggle="example-menu"></button>
            </div>
            
        </div>
            
        <div class="top-bar grid-x show-for-small-only" id="example-menu">           
            <div class="cell medium-shrink">
                <ul class="menu medium-horizontal large-horizontal" data-responsive-menu="small-accordion medium-dropdown" style="width: 100%;">
                    <li class= {{ homstat }}><a href="{% url 'myweb:index' %}">Timeline</a></li>
                    <li class= {{ porstat }}><a href="{% url 'myweb:portofolio' %}">Portofolio</a></li>
                    <li class= {{ abtstat }}><a href="{% url 'myweb:about' %}">About</a></li>
                    <li class= {{ msgstat }}><a href="{% url 'myweb:message' %}">Message</a></li>
                    <li class= {{ scdstat }}><a href="{% url 'myweb:view_sched' %}">Schedule</a></li>
                    <li><a style="padding: 12px 15px 12px 15px; fill: #ffffff" href="{% url 'myweb:login' %}"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 0c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm7.753 18.305c-.261-.586-.789-.991-1.871-1.241-2.293-.529-4.428-.993-3.393-2.945 3.145-5.942.833-9.119-2.489-9.119-3.388 0-5.644 3.299-2.489 9.119 1.066 1.964-1.148 2.427-3.393 2.945-1.084.25-1.608.658-1.867 1.246-1.405-1.723-2.251-3.919-2.251-6.31 0-5.514 4.486-10 10-10s10 4.486 10 10c0 2.389-.845 4.583-2.247 6.305z"/></svg></a></li>
                </ul>
                
            </div>
        </div>
        
        <div id="container-home">
            <div class="float-profile-self align-center grid-x color">
                <div class="prof-pic">
                </div>
                <div class="show-for-large prof-detail">
                    <h4>ABOUT</h4>
                    <p class="text-justify"> Curios and organized person
                        who has passion in technology,
                        great listener, enjoy ...
                    </p style="padding: 10px">

                    <h6>
                        <a href="{% url 'myweb:about' %}">Read more...</a>
                    </h6>

                    <h4 class="text-center"> ______________ </h4>
                    <br>
                    <svg style="fill: #0077b5" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 2c5.514 0 10 4.486 10 10s-4.486 10-10 10-10-4.486-10-10 4.486-10 10-10zm0-2c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm-2 8c0 .557-.447 1.008-1 1.008s-1-.45-1-1.008c0-.557.447-1.008 1-1.008s1 .452 1 1.008zm0 2h-2v6h2v-6zm3 0h-2v6h2v-2.861c0-1.722 2.002-1.881 2.002 0v2.861h1.998v-3.359c0-3.284-3.128-3.164-4-1.548v-1.093z"/></svg>
                    <p style="display: inline-block; vertical-align: middle">linkedin.com/in/aryo-tinulardhi</p>                    
                    <br>
                    <svg style="fill: #d9534f" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 2.02c5.514 0 10 4.486 10 10s-4.486 10-10 10-10-4.486-10-10 4.486-10 10-10zm0-2c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm0 12.55l-5.992-4.57h11.983l-5.991 4.57zm0 1.288l-6-4.629v6.771h12v-6.771l-6 4.629z"/></svg>
                    <p style="display: inline-block; vertical-align: middle">aryo.tinulardhi@ui.ac.id</p>   
                    <br>
                    <svg style="fill: #25d366" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 2c5.514 0 10 4.486 10 10s-4.486 10-10 10-10-4.486-10-10 4.486-10 10-10zm0-2c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm4.5 17.311l-1.76-3.397-1.032.505c-1.12.543-3.4-3.91-2.305-4.497l1.042-.513-1.747-3.409-1.053.52c-3.601 1.877 2.117 12.991 5.8 11.308l1.055-.517z"/></svg>
                    <p style="display: inline-block; vertical-align: middle">(+62)813-2251-7737</p> 

                </div>
            </div>


            <div class="show-for-large float-name-self grid-x">
                <div class="name">
                    <h1 style="color: #34495E">ARYO TINULARDHI</h1>
                </div>
            </div>


            <div class="header">
                <div class="img-header">
                    <div class="header-image">

                    </div>
                    <div class="header-name">
                        
                    </div>
                </div>
                <div class="profile">
                    <div class="prof-pic1">

                    </div>
                    <div class="biodata">
                        
                    </div>
                </div>
                <div class="head-bar">
                    <div class="detail">
                        <div style="text-align: center;" class="hide-for-medium name-medium-small-self">
                            <h1>ARYO TINULARDHI</h1>
                        </div>
                        <div class="grid-x show-for-large" style="margin: 0 0 0 450px; padding: 10px; color: #ffffff;">
                            <div class="cell auto">
                               <h3>AGE</h3>
                               <h1 style="font-size: 4rem">19</h1>
                            </div>
                            <div class="cell auto">
                                <h3>PROJECT</h3>
                                <h1 style="font-size: 4rem">15</h1>
                            </div>
                            <div class="cell auto">
                                <h3>COUNTRY</h3>
                                <h1 style="font-size: 4rem">ID</h1>
                            </div>
                        </div>
                    </div>
                    <nav class="menu-bar top-bar show-for-medium" style="background-color: #30C2FF" data-topbar role="navigation">
                        <section class="menu-bar-self top-bar-section top-bar-left">
                        <!-- Right Nav Section -->
                            <ul class="medium-horizontal left no-bullet menu">
                                <li class= {{ homstat }}><a href="{% url 'myweb:index' %}">Timeline</a></li>
                                <li class= {{ porstat }}><a href="{% url 'myweb:portofolio' %}">Portofolio</a></li>
                                <li class= {{ abtstat }}><a href="{% url 'myweb:about' %}">About</a></li>
                                <li class= {{ msgstat }}><a href="{% url 'myweb:message' %}">Message</a></li>
                                <li class= {{ scdstat }}><a href="{% url 'myweb:view_sched' %}">Schedule</a></li>
                                <li><a style="padding: 12px 15px 12px 15px; fill: #ffffff" href="{% url 'myweb:login' %}"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 0c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm7.753 18.305c-.261-.586-.789-.991-1.871-1.241-2.293-.529-4.428-.993-3.393-2.945 3.145-5.942.833-9.119-2.489-9.119-3.388 0-5.644 3.299-2.489 9.119 1.066 1.964-1.148 2.427-3.393 2.945-1.084.25-1.608.658-1.867 1.246-1.405-1.723-2.251-3.919-2.251-6.31 0-5.514 4.486-10 10-10s10 4.486 10 10c0 2.389-.845 4.583-2.247 6.305z"/></svg></a></li>
                            </ul>
                        </section>
                    </nav>
                </div>
            </div>

            {% block main %}
            {% endblock %}
        </div>


        <script src="{%static "js/app.js" %}"></script>
        <script src="{%static "js/vendor/jquery.js" %}"></script>
        <script src="{%static "js/vendor/foundation.js" %}"></script>
    </body>
</html>

myweb/templates/base2.html
{% load static %}
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        
        <link href="https://fonts.googleapis.com/css?family=Karla:700" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{%static "css/app.css" %}">
        <link rel="stylesheet" type="text/css" href="{%static "css/foundation.css" %}">
        <link rel="stylesheet" type="text/css" href="{%static "css/foundation.min.css" %}">
        <link rel="stylesheet" type="text/css" href="{%static "css/style.css" %}">
        <link rel="stylesheet" type="text/css" href="{%static "css/styleacc.css" %}">

        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" rel="stylesheet">
        <title>
            {{ title }}
        </title>
        <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    </head>
    <body style="">
        <div class="login-wrapper">
        </div>
            
        <!-- Navbar -->
        <div class="title-bar grid-x" data-responsive-toggle="example-menu" data-hide-for="medium">
            <div class="cell small-6">
                <h1> {{ title }} </h1>
            </div>
                
            <div class="logo-self cell small-6">
                <button class="menu-icon" type="button" data-toggle="example-menu"></button>
            </div>
            
        </div>
            
        <div class="top-bar grid-x" id="example-menu">
            <div class="cell shrink hide-for-small-only">
                <div class="cell small-6">
                    <h4> {{ title }} </h4>
                </div>
            </div>
                

            <div class="cell medium-shrink">
                <ul class="menu medium-horizontal large-horizontal" data-responsive-menu="small-accordion medium-dropdown" style="width: 100%;">
                    <li><a href="{% url 'myweb:index' %}">Home</a></li>
                    <li><a href="{% url 'myweb:view_sched' %}">Schedule</a></li>
                    <li><a href="{% url 'myweb:signup' %}">Register</a></li>
                </ul>
            </div>
        </div>


        {% block main %}
        {% endblock %}

        <script src="{%static "js/app.js" %}"></script>
        <script src="{%static "js/vendor/jquery.js" %}"></script>
        <script src="{%static "js/vendor/foundation.js" %}"></script>
    </body>
</html>

myweb/templates/create_sched.html
{% extends 'base2.html' %}

{% block main %}
<div class="grid-x" style="margin: 20px">
    <div class="cell small-1">

    </div>
    <div  style="background: #eaeaea; padding: 25px; border-radius: 30px" class="cell small-10">
        <section name="form">
            <h2 style="color: #2c3e50">Create Schedule</h2>
            <form action="{% url 'myweb:sched_post' %}" id="form", method="POST">
                {% csrf_token %}
                {{ schedule_form }}
                <br>
                <button type="submit" class="button">Submit</button>
            </form>
        </section>
    </div>
    <div class="cell small-1"></div>

</div>
{% endblock %}

myweb/templates/login.html
{% extends "base2.html" %}

{% block main %}
<div id="content-login">
    
    <div class="login-self grid-x align-center">
        <div class="cell large-4">

        </div>
        <div style="max-width: 380px; border-radius: 20px; padding: 25px 0" class="login-sec cell large-4">
            
            <div class="login-landing grid-x align-center">
                <h3>Login<br>
                    <svg style="align-center" width="24" height="24" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" clip-rule="evenodd"><path d="M24 11.5c0 3.613-2.951 6.5-6.475 6.5-2.154 0-4.101-1.214-5.338-3h-2.882l-1.046-1.013-1.302 1.019-1.362-1.075-1.407 1.081-4.188-3.448 3.346-3.564h8.841c1.145-1.683 3.104-3 5.339-3 3.497 0 6.474 2.866 6.474 6.5zm-10.691 1.5c.98 1.671 2.277 3 4.217 3 2.412 0 4.474-1.986 4.474-4.5 0-2.498-2.044-4.5-4.479-4.5-2.055 0-3.292 1.433-4.212 3h-9.097l-1.293 1.376 1.312 1.081 1.38-1.061 1.351 1.066 1.437-1.123 1.715 1.661h3.195zm5.691-3.125c.828 0 1.5.672 1.5 1.5s-.672 1.5-1.5 1.5-1.5-.672-1.5-1.5.672-1.5 1.5-1.5z"/></svg>
                </h3>
                <div class="cell large-12 columns" style="padding: 0 30px 0 30px">
                    <input type="text" placeholder="Username" />
                </div>
                <div class="cell large-12 columns" style="padding: 0 30px 0 30px">
                    <input type="password" placeholder="Password" />
                </div>
                <p class="text-center"><a href="{% url 'myweb:signup' %}">or register</a></p>
                <div class="cell large-12 columns" style="padding: 0 30px 0 30px">
                    <a class="button expanded" href="#">Login</a>
                </div>
                <p class="text-right"><a href="#">Forgot password?</a></p>
            </div>
            
        </div>
        <div class="cell large-4">
            
        </div>                
    </div>

</div>
{% endblock %}

myweb/templates/message.html
{% extends "base.html" %}

{% block main %}

<div class="content grid-x">
    <div class="cell medium-4" style="background-color: #ECF0F1">

    </div>
    <div class="cell medium-7 message-self">
        <div class="grid-x">
            <div class="cell large-12 columns">
                <h2>Send me a message!</h2>
                <br>    
            </div>

            <div class="cell large-6 columns" style="padding: 0 10px 0 10px">
                <input type="text" placeholder="Name" />
            </div>

            <div class="cell large-6 columns" style="padding: 0 10px 0 10px">            
                <input type="text" placeholder="Email" />
            </div>
            
            <div class="cell large-12 columns"  style="padding: 0 10px 0 10">
                <textarea placeholder="Write your message here!" style="height: 200px"></textarea>
            </div>

            <div class="cell large-12 columns" style="padding: 0 10px;">
                <a class="button expanded" href="#">Submit</a>
            </div>
        </div>
        
    </div>
    
</div>

{% endblock %}

myweb/templates/sched_uploaded.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Document</title>
    </head>
    <body>
        {% block content %}
        <h2>Terima kasih!</h2>
        {% endblock %}
        
        {% block footer %}
        {% endblock %}    
    </body>
</html>

myweb/templates/view_sched.html
{% extends 'base2.html' %}
{% block main %}
<!--  Populate semua isi pesan dari model -->
<div style= {{ showpopup }} id="thover"></div>
 
    <div style= {{ showpopup }} id="tpopup">
    <h2> {{ word }} </h2> 

    <div id="tclose">X</div>    
</div>
<div id="content-login">
    <div style="margin: 30px 0 0 10px" class="grid-x align-middle">
        <div class="cell small-1">

        </div>
        <div class="cell small-5">
            <h2 style="color: #ecf0f1;">Our Schedule</h2> 
        </div>
        <div class="cell small-5 float-right">
            <a class="button float-right" href="{% url 'myweb:create_sched' %}">Add</a>
        </div>
        <div class="cell small-1">

        </div>
    </div>
    {% for i in schedule %}
    <div style="padding: 10px 0; margin: 2px 0;" class="login-self grid-x align-center">
        
        <div class="cell small-1">

        </div>
        
        <div class="item-event cell small-10 grid-x align-middle">
            
                <div class="cell medium-4"> <h4> {{i.event_name}} </h4> </div>
                <div class="cell medium-2"> {{i.event_date}} <br> {{i.event_time}} </div>
                <div class="cell medium-3"> {{i.event_category}} </div>
                <div class="cell medium-3"> {{i.event_place}} </div>        
        
        </div>
        
        <div class="cell small-1">
            
        </div>
    </div>
    {% endfor %}
    <div class="grid-x align-center">
        
            <div class="cell small-1">
    
            </div>
            
            <div class="cell small-10 grid-x align-middle">
                <a class="button expanded" href="{% url 'myweb:delete_all_sched_db' %}">Delete All</a>  
            </div>
            
            <div class="cell small-1">
                
            </div>
        </div>
</div>
<script>
    $(document).ready(function(){
  
    $("#thover").click(function(){
        $(this).fadeOut();
        $("#tpopup").fadeOut();
    });
  
  
    $("#tclose").click(function(){
        $("#thover").fadeOut();
        $("#tpopup").fadeOut();
	});
  
});
</script>


{% endblock %}